version: '3.3'
services:
  web:
    build: .
    stdin_open: true
    tty: true
    depends_on:
      - db
    ports:
      - "5000:5000"
    container_name: flask_app
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_HOST: flask_app_db
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: root
      SECRET_KEY: 'you-will-never-guess'

  db:
    image: mysql:5.7
    restart: always
    container_name: flask_app_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    volumes:
      - mysql57_data:/var/lib/mysql
volumes:
  mysql57_data:
